name_conversion_dict = {
    'Gabriel Jesus': 'Gabriel Fernando de Jesus',
    'Gabriel Martinelli': 'Gabriel Martinelli Silva',
    'Philippe Coutinho': 'Philippe Coutinho Correia',
    'Emiliano Buendia': 'Emiliano Buendia Stati',
    'Ayoze': 'Ayoze Perez',
    'Douglas Luiz': 'Douglas Luiz Soares de Paulo',
    'Gabriel': 'Gabriel dos Santos Magalhaes',
    'Vitaliy Mykolenko': 'Vitalii Mykolenko',
    'Ruben Vinagre': 'Ruben Nascimento Vinagre',
    'Ezri Konsa': 'Ezri Konsa Ngoyo',
    'Diego Carlos': 'Diego Carlos Santos Silva',
    'White, Ben': 'Benjamin White',
    'Allan': 'Allan Marques Loureiro',
    'Erling Braut Haaland': 'Erling Haaland',
    'Darwin Nunez': 'Darwin Nunez Ribeiro',
    'Bernardo Silva': 'Bernardo Veiga de Carvalho e Silva',
    'Cristiano Ronaldo': 'Cristiano Ronaldo dos Santos Aveiro',
    'Bruno Fernandes': 'Bruno Borges Fernandes',
    'Manuel Goncalo Guedes': 'Goncalo Manuel Ganchinho Guedes',
    'Cavaco Joao Cancelo': 'Joao Cancelo',
    'Pedro Neto': 'Pedro Lomba Neto',
    'Pablo Fornals': 'Pablo Fornals Malla',
    'Andy Robertson': 'Andrew Robertson',
    'Richarlison': 'Richarlison de Andrade',
    'Daniel Podence': 'Daniel Castelo Podence',
    'Joe Aribo': 'Joe Ayodele-Aribo',
    'Adama Traore': 'Adama Traore Diarra',
    'Ivan Cavaleiro': 'Ivan Neves Abreu Cavaleiro',
    'Andreas Pereira': 'Andreas Hoelgebaum Pereira',
    'Donny Van de Beek': 'Donny van de Beek',
    'Bruno Guimaraes': 'Bruno Guimaraes Rodriguez Moura',
    'Lucas Moura': 'Lucas Rodrigues Moura da Silva',
    'Jeremy Sarmiento': 'Jeremy Sarmiento Morante',
    'Rodri': 'Rodrigo Hernandez',
    'Ruben Neves': 'Ruben da Silva Neves',
    'Bryan Gil': 'Bryan Gil Salvatierra',
    'Facundo Pellistri': 'Facundo Pellistri Rebollo',
    'Marc Cucurella': 'Marc Cucurella Saseta',
    'Miguel Almiron': 'Miguel Almiron Rejala',
    'Joao Palhinha': 'Joao Palhinha Goncalves',
    'Felipe Joao Moutinho': 'Joao Filipe Iria Santos Moutinho',
    'Oriol Romeu': 'Oriol Romeu Vidal',
    'Marc Roca': 'Marc Roca Junque',
    'Pierre Hojbjerg': 'Pierre-Emile Hojbjerg',
    'Luke Mbete': 'Luke Mbete-Tabu',
    'Diogo Dalot': 'Diogo Dalot Teixeira',
    'NGolo Kante': "N'Golo Kante",
    'Ruben Dias': 'Ruben Gato Alves Dias',
    'Emerson': 'Emerson Palmieri dos Santos',
    'Nelson Semedo': 'Nelson Cabral Semedo',
    'Mads Roerslev': 'Mads Roerslev Rasmussen',
    'Leo Hjelde': 'Leo Fuhr Hjelde',
    'Thiago Silva': 'Thiago Emiliano da Silva',
    'Jefferson Lerma': 'Jefferson Lerma Solis',
    'Hwang Hee-Chan' : 'Hwang Hee-chan',
    'Filho Jorge Jorginho' : 'Jorge Luiz Frello Filho',
    'Joelinton': 'Joelinton Cassio Apolinario de Lira',
    'Fabio Carvalho': 'Fabio Freitas Gouveia Carvalho',
    'Joe Gomez': 'Joseph Gomez',
    'Junior Firpo': 'Junior Firpo Adames',
    'Luis Sinisterra': 'Luis Sinisterra Lucumi',
    'Cheick Oumar Doucoure': 'Cheick Doucoure',
    'Javier Manquillo': 'Javier Manquillo Gaitan',
    'Pape Sarr': 'Pape Matar Sarr',
    'Hugo Bueno': 'Hugo Bueno Lopez',
    'Jonny': 'Jonny Evans',
    'Lyanco': 'Lyanco Silveira Neves Vojnovic',
    'Matheus Nunes': 'Matheus Luiz Nunes',
    'Toti': 'Toti Antonio Gomes',
    'Yerson Mosquera': 'Yerson Mosquera Valdelamar',
    'Moises Caicedo': 'Moises Caicedo Corozo',
    'Cedric Soares': 'Cedric Alves Soares',
    'Fabio Vieira': 'Fabio Ferreira Vieira',
    'Frederico Fred': 'Frederico Rodrigues de Paula Santos',
    'Diogo Jota': 'Diogo Teixeira da Silva',
    'Fabinho': 'Fabio Henrique Tavares',
    'Lucas Paqueta': 'Lucas Tolentino Coelho de Lima',
    'Emerson Royal': 'Emerson Leite de Souza Junior',
    'Antony': 'Antony Matheus dos Santos',
    'Casemiro': 'Carlos Henrique Casimiro',
    'Willian': 'Willian Borges da Silva',
    'Sergi Canos': 'Sergi Canos Tenes',
    'Diego Costa': 'Diego Da Silva Costa',
    'Renan Lodi': 'Renan Augusto Lodi dos Santos',
    'Luis Sinisterr': 'Luis Sinisterra Lucumi',
    'Thiago': 'Thiago Alcantara do Nascimento',    
}